In [1]:
import pandas as pd
import requests
from API_Key import api_key
titleNid = pd.read_csv("Tables/titleNid.csv")

In [2]:
famous_actors = pd.DataFrame()
id_for_movie = []

for movie_id in titleNid['id']:
    movie = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key={api_key}&language=en-US').json()
    for popular in movie['cast']:
        if popular["popularity"] >=10:
            famous_actors = famous_actors.append(popular,ignore_index = True)
            id_for_movie.append(movie_id)

In [3]:
famous_actors["movie_id"] = id_for_movie
famous_actors

,adult,cast_id,character,credit_id,gender,id,known_for_department,name,order,original_name,popularity,profile_path,movie_id
0,0.0,11.0,Shaun / Shang-Chi,5d33b7e66a300b2f7ea6bc88,2.0,1489211.0,Acting,Simu Liu,0.0,Simu Liu,31.712,/zrJjYjOYzDj7eY9oiHAoz8Yh0yk.jpg,566525
1,0.0,12.0,Xu Wenwu,5d33c5fc2f8d094522dbaf68,2.0,1337.0,Acting,Tony Leung Chiu-wai,1.0,Tony Leung Chiu-wai,48.554,/nQbSQAws5BdakPEB5MtiqWVeaMV.jpg,566525
2,0.0,10.0,Katy Chen,5d33b71fcaab6d0b29a8a566,1.0,1625558.0,Acting,Awkwafina,2.0,Awkwafina,41.972,/l5AKkg3H1QhMuXmTTmq1EyjyiRb.jpg,566525
3,0.0,61.0,Xu Xialing,602b041de72fe8003c101fca,1.0,2979464.0,Acting,Meng'er Zhang,3.0,Meng'er Zhang,20.931,/yMiYThzzkeVSsUI2sxh3iIWmMTy.jpg,566525
4,0.0,54.0,Ying Li,5f5a4014ec0c580035a40140,1.0,123701.0,Acting,Fala Chen,4.0,Fala Chen,10.698,/1eoEj3umXbxUkTXb5c7bmC3EUTh.jpg,566525
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,0.0,3.0,Ria,52fe46389251416c75071333,1.0,39126.0,Acting,Bai Ling,4.0,Bai Ling,10.332,/PXbFNTUbC3aoLrquCzFaxdF2ev.jpg,15092
453,1.0,140.0,Female Porn Star,59cb9c6ec3a36877a900f8f0,1.0,135586.0,Acting,Monique Alexander,49.0,Monique Alexander,20.845,/1UuzAFE2umbzL5Gvy5yJOLxepOb.jpg,15092
454,0.0,3.0,Bea,5e5f087b303c8500193dd747,1.0,33397.0,Acting,Sarah Bolger,3.0,Sarah Bolger,13.111,/A3K2l5kkqTMQHtAkctzICqtbZMY.jpg,680319
455,0.0,0.0,Greville Wynne,5aebb9ea0e0a266e2c00120d,2.0,71580.0,Acting,Benedict Cumberbatch,0.0,Benedict Cumberbatch,19.006,/fBEucxECxGLKVHBznO0qHtCGiMO.jpg,522241
456,0.0,2.0,Megumin (voice),5b30d2df0e0a26401100116b,1.0,1492982.0,Acting,Rie Takahashi,2.0,Rie Takahashi,11.024,/zJRLMHKtZvgyJ2GtTfiJTeKdudc.jpg,532067

In [10]:
#famous_actors[famous_actors['name'].str.contains("Hardy")]
titleNid

         id                                              title
0    566525          Shang-Chi and the Legend of the Ten Rings
1    370172                                     No Time to Die
2    580489                        Venom: Let There Be Carnage
3    522402                                              Finch
4    763164                                               Apex
..      ...                                                ...
195  159211                             The Haunting of Helena
196  522241                                        The Courier
197  532067  KonoSuba: God's Blessing on this Wonderful Wor...
198  763873                                        Under Wraps
199  623135                                           Sinkhole

[200 rows x 2 columns]

In [4]:
famous_actors.count()

adult                   457
cast_id                 457
character               457
credit_id               457
gender                  457
id                      457
known_for_department    457
name                    457
order                   457
original_name           457
popularity              457
profile_path            457
movie_id                457
dtype: int64

In [19]:
famous_actors = famous_actors.rename(columns = {"id": "actor_id",'popularity': 'actor_popularity'})

In [25]:
famous_actors_cleaned = famous_actors[['name','actor_id','gender','character','actor_popularity','movie_id']]
famous_actors_cleaned

,name,actor_id,gender,character,actor_popularity,movie_id
0,Simu Liu,1489211.0,2.0,Shaun / Shang-Chi,31.712,566525
1,Tony Leung Chiu-wai,1337.0,2.0,Xu Wenwu,48.554,566525
2,Awkwafina,1625558.0,1.0,Katy Chen,41.972,566525
3,Meng'er Zhang,2979464.0,1.0,Xu Xialing,20.931,566525
4,Fala Chen,123701.0,1.0,Ying Li,10.698,566525
...,...,...,...,...,...,...
452,Bai Ling,39126.0,1.0,Ria,10.332,15092
453,Monique Alexander,135586.0,1.0,Female Porn Star,20.845,15092
454,Sarah Bolger,33397.0,1.0,Bea,13.111,680319
455,Benedict Cumberbatch,71580.0,2.0,Greville Wynne,19.006,522241
456,Rie Takahashi,1492982.0,1.0,Megumin (voice),11.024,532067

In [12]:
directors = pd.DataFrame()
director_movie_id = []

for movie_id in titleNid['id']:
    movie  = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key={api_key}&language=en-US').json()
    for crew_member in movie['crew']:
        if crew_member['job'] == "Director":
            directors = directors.append(crew_member, ignore_index=True)
            director_movie_id.append(movie_id)

In [22]:
directors['movie_id'] = director_movie_id
directors = directors.rename(columns={'id': 'director_id', 'popularity': 'director_popularity'})
directors

,adult,credit_id,department,gender,director_id,job,known_for_department,name,original_name,director_popularity,profile_path,movie_id
0,0.0,5c8965e39251410cf7c195f6,Directing,2.0,1144604.0,Director,Directing,Destin Daniel Cretton,Destin Daniel Cretton,4.780,/6pOwxAXGsaqjlJmAdz9k3UArBdS.jpg,566525
1,0.0,5ba362e80e0a265e50015bba,Directing,2.0,87257.0,Director,Directing,Cary Joji Fukunaga,Cary Joji Fukunaga,5.024,/qhrtYCUM2NEaqVP3oB7vqkOTpx0.jpg,370172
2,0.0,5e866a52a5743d00180fe64e,Directing,2.0,1333.0,Director,Acting,Andy Serkis,Andy Serkis,14.521,/2aJLwOQK50Lx7PvIHGW1GMytTOL.jpg,580489
3,0.0,5aecfbbb9251411d1e0022db,Directing,2.0,114404.0,Director,Directing,Miguel Sapochnik,Miguel Sapochnik,2.707,/jlZGTjiifvvFDoEtlwrKz7QxuJS.jpg,522402
4,0.0,613103d5ab68490029ae70df,Directing,2.0,2613318.0,Director,Directing,Edward Drake,Edward Drake,1.266,None,763164
...,...,...,...,...,...,...,...,...,...,...,...,...
213,0.0,52fe4c079251416c910ed689,Directing,0.0,1140975.0,Director,Visual Effects,Ascanio Malgarini,Ascanio Malgarini,0.600,None,159211
214,0.0,5aebb9f9c3a36872040017e2,Directing,2.0,1539858.0,Director,Directing,Dominic Cooke,Dominic Cooke,1.400,None,522241
215,0.0,5b3272720e0a263ffc00f230,Directing,0.0,1281402.0,Director,Directing,Takaomi Kanasaki,Takaomi Kanasaki,1.227,None,532067
216,0.0,5faebe18ad59b5003d5a6746,Directing,2.0,88077.0,Director,Directing,Alex Zamm,Alex Zamm,1.400,/aqV83qLyqEqr7NEi9ncyNcfago7.jpg,763873
217,0.0,5d53cc936dc6c0647b98881e,Directing,2.0,583166.0,Director,Directing,Kim Ji-hoon,Kim Ji-hoon,1.532,/eJr6Bzo45mR8CDCrecjYpJIZObz.jpg,623135

In [24]:
director_clean = directors[['name','director_id','gender','director_popularity','movie_id']]
director_clean

                      name  director_id  gender  director_popularity  movie_id
0    Destin Daniel Cretton    1144604.0     2.0                4.780    566525
1       Cary Joji Fukunaga      87257.0     2.0                5.024    370172
2              Andy Serkis       1333.0     2.0               14.521    580489
3         Miguel Sapochnik     114404.0     2.0                2.707    522402
4             Edward Drake    2613318.0     2.0                1.266    763164
..                     ...          ...     ...                  ...       ...
213      Ascanio Malgarini    1140975.0     0.0                0.600    159211
214          Dominic Cooke    1539858.0     2.0                1.400    522241
215       Takaomi Kanasaki    1281402.0     0.0                1.227    532067
216              Alex Zamm      88077.0     2.0                1.400    763873
217            Kim Ji-hoon     583166.0     2.0                1.532    623135

[218 rows x 5 columns]

In [14]:
directors.count()

adult                   218
credit_id               218
department              218
gender                  218
id                      218
job                     218
known_for_department    218
name                    218
original_name           218
popularity              218
profile_path            139
movie_id                218
dtype: int64